# gui requirements
sudo: required

language: python
# python versions to use during the tests
python:
  - "3.7"

addons:
  apt:
    packages:
      - x11-utils
      - libxkbcommon-x11-0
      - xvfb
      - herbstluftwm # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#xvfb-assertionerror-timeouterror-when-using-waituntil-waitexposed-and-ui-events
      - qt5-default
      - qttools5-dev-tools

services:
  - xvfb
  - herbstluftwm

env:
  - DISPLAY=":99.0" # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html?highlight=travis#xvfb-assertionerror-timeouterror-when-using-waituntil-waitexposed-and-ui-events

install:
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U coveralls
  - pip install -U numpy
  - pip install -U PySide2
  - pip install -U pyqtgraph>=0.11.0rc0
  - pip install -e .

# command to run tests
before_script:
  - mkdir -p /home/travis/vent/logs # make directories for logs
script:
  - pytest --cov=vent --cov-report term-missing tests
after_success:
  - coveralls
