# gui requirements
sudo: required


language: python
# python versions to use during the tests
python:
  - "3.7"
before_install:
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U coveralls

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files
  - pip install -U PySide2
  - pip install -U pyqtgraph>=0.11.0rc0
  - pip install -e .

# command to run tests
script:
  - pytest --cov=vent --cov-report term-missing tests
after_success:
  - coveralls
